export const CHAINS_MAIN = [
  {
    key: 'btc',
    chain_id: '0',
    sort: 1,
    id: '6',
    name: 'Bitcoin',
    coin: 'BTC',
    gas: '0.0001',
  },
  {
    key: 'eth',
    chain_id: '1',
    sort: 2,
    id: '1',
    name: 'Ethereum',
    coin: 'ETH',
    gas: '0.0005',
  },
  {
    key: 'bnb',
    chain_id: '56',
    sort: 3,
    id: '2',
    name: 'Binance',
    coin: 'BNB',
    gas: '0.005',
  },
  {
    key: 'pol',
    chain_id: '137',
    sort: 4,
    id: '4',
    name: 'Polygon',
    coin: 'ETH',
    gas: '0.0005',
  },
  {
    key: 'arb',
    chain_id: '42161',
    sort: 5,
    id: '3',
    name: 'Arbitrum',
    coin: 'ETH',
    gas: '0.0005',
  },
  {
    key: 'tron',
    chain_id: '1231',
    sort: 6,
    id: '7',
    name: 'Tron',
    coin: 'TRON',
    gas: '0.05',
  },
  {
    key: 'ltc',
    chain_id: '0',
    sort: 7,
    id: '8',
    name: 'Litecoin',
    coin: 'LTC',
    gas: '0.01',
  },
  {
    key: 'sol',
    chain_id: '0',
    sort: 8,
    id: '9',
    name: 'Solana',
    coin: 'SOL',
    gas: '0.00005',
  },
  {
    key: 'xtz',
    chain_id: 'NetXazhm4yetmff',
    sort: 9,
    id: '10',
    name: 'Tezos',
    coin: 'XTZ',
    gas: '0.05',
  },
  { key: 'opt', chain_id: '10', sort: 10, id: '5', name: 'Optimism', coin: 'ETH', gas: '0.0005' },
];

export const CHAINS_TEST = [
  {
    key: 'btc',
    chain_id: '0',
    sort: 1,
    id: '6',
    name: 'Bitcoin',
    coin: 'BTC',
    gas: '0.0001',
  },
  {
    key: 'eth',
    chain_id: '5',
    sort: 2,
    id: '1',
    name: 'Ethereum',
    coin: 'ETH',
    gas: '0.0005',
  },
  {
    key: 'bsc',
    chain_id: '97',
    sort: 3,
    id: '2',
    name: 'Binance',
    coin: 'BNB',
    gas: '0.005',
  },
  {
    key: 'pol',
    chain_id: '80001',
    sort: 4,
    id: '4',
    name: 'Polygon',
    coin: 'ETH',
    gas: '0.0005',
  },
  {
    key: 'arb',
    chain_id: '421613',
    sort: 5,
    id: '3',
    name: 'Arbitrum',
    coin: 'ETH',
    gas: '0.0005',
  },
  {
    key: 'tron',
    chain_id: '1230',
    sort: 6,
    id: '7',
    name: 'Tron',
    coin: 'TRON',
    gas: '0.05',
  },
  {
    key: 'ltc',
    chain_id: '0',
    sort: 7,
    id: '8',
    name: 'Litecoin',
    coin: 'LTC',
    gas: '0.01',
  },
  {
    key: 'sol',
    chain_id: '0',
    sort: 8,
    id: '9',
    name: 'Solana',
    coin: 'SOL',
    gas: '0.00005',
  },
  {
    key: 'xtz',
    chain_id: 'NetXazhm4yetmff',
    sort: 9,
    id: '10',
    name: 'Tezos',
    coin: 'XTZ',
    gas: '0.05',
  },
  {
    key: 'opt',
    chain_id: '420',
    sort: 10,
    id: '5',
    name: 'Optimism',
    coin: 'ETH',
    gas: '0.0005',
  },
];
